# openapi.yml

openapi: 3.0.3
info:
  title: Item Manager API
  description: API for managing items with full CRUD operations.
  version: 1.0.0

servers:
  - url: http://localhost:5001

paths:
  /api/items:
    get:
      summary: List all items
      responses:
        "200":
          description: A list of items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Item"
    post:
      summary: Create a new item
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ItemInput"
      responses:
        "201":
          description: Item created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"

  /api/items/{id}:
    get:
      summary: Get a single item by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Item found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
        "404":
          description: Item not found
    put:
      summary: Update an existing item
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ItemInput"
      responses:
        "200":
          description: Item updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
        "404":
          description: Item not found
    delete:
      summary: Delete an item by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: Item deleted
        "404":
          description: Item not found

components:
  schemas:
    Item:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "Sample Item"
        description:
          type: string
          example: "This is a sample item."
        createdAt:
          type: string
          format: date-time
          example: "2025-06-27T10:00:00Z"
        updatedAt:
          type: string
          format: date-time
          example: "2025-06-27T10:00:00Z"
    ItemInput:
      type: object
      properties:
        name:
          type: string
          example: "Sample Item"
        description:
          type: string
          example: "This is a sample item."
      required:
        - name
