name: Keploy API Tests

on: [push, pull_request]

jobs:
  keploy-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Clean install dependencies
        run: |
          cd backend
          rm -rf node_modules package-lock.json
          npm install

      - name: Install Keploy CLI
        run: |
          curl -s https://keploy.io/install.sh | bash -x
          find $HOME -type f -name keploy

      - name: Add Keploy to PATH
        run: |
          export KEPLOY_PATH=$(find $HOME -type f -name keploy | xargs dirname)
          echo "$KEPLOY_PATH" >> $GITHUB_PATH

      - name: Check Keploy version
        run: keploy version

      - name: Run Keploy tests
        run: |
          cd backend
          keploy test -c "npm start" --delay 5
