# .github/workflows/keploy-ci.yml

name: Keploy API Tests

on: [push, pull_request]

jobs:
  keploy-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: false  # Set to true only if you use submodules

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Clean install dependencies
        run: |
          cd backend
          rm -rf node_modules package-lock.json
          npm install

      - name: Start API server
        run: |
          cd backend
          nohup npm start &
          sleep 5

      - name: Install Keploy CLI
        run: |
          curl -s https://keploy.io/install.sh | bash
          echo "$HOME/.keploy/bin" >> $GITHUB_PATH
          export PATH="$HOME/.keploy/bin:$PATH"

      - name: Check Keploy version
        run: |
          export PATH="$HOME/.keploy/bin:$PATH"
          keploy version

      - name: Run Keploy tests
        run: |
          cd backend
          export PATH="$HOME/.keploy/bin:$PATH"
          keploy test -c "npm start" --delay 5
