# .github/workflows/keploy-ci.yml
name: Keploy API Tests

on: [push, pull_request]

jobs:
  keploy-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Start API server
        run: |
          cd backend
          nohup npm start &
          sleep 5

      - name: Install Keploy
        run: |
          curl --silent --location "https://github.com/keploy/keploy/releases/latest/download/keploy-linux-amd64" --output keploy
          chmod +x keploy
          sudo mv keploy /usr/local/bin/

      - name: Run Keploy tests
        run: |
          cd backend
          keploy test -c "npm start" --delay 5
